b'def celsius_to_fahrenheit(celsius):\n    """Convert Celsius to Fahrenheit.\"\n    if not isinstance(celsius, (int, float)):\n        raise TypeError("Input must be a numeric value.")\n    return (celsius * 9/5) + 32\n\ndef fahrenheit_to_celsius(fahrenheit):\n    """Convert Fahrenheit to Celsius.\"\n    if not isinstance(fahrenheit, (int, float)):\n        raise TypeError("Input must be a numeric value.")\n    return (fahrenheit - 32) * 5/9\n\ndef celsius_to_kelvin(celsius):\n    """Convert Celsius to Kelvin.\"\n    if not isinstance(celsius, (int, float)):\n        raise TypeError("Input must be a numeric value.")\n    return celsius + 273.15'

b'import pytest\nfrom converters import celsius_to_fahrenheit, fahrenheit_to_celsius, celsius_to_kelvin\n\ndef test_celsius_to_fahrenheit():\n    assert celsius_to_fahrenheit(0) == 32.0\n    assert celsius_to_fahrenheit(100) == 212.0\n    assert celsius_to_fahrenheit(25) == 77.0\n    with pytest.raises(TypeError):\n        celsius_to_fahrenheit("string")\n    with pytest.raises(TypeError):\n        celsius_to_fahrenheit(None)\n\ndef test_fahrenheit_to_celsius():\n    assert fahrenheit_to_celsius(32) == 0.0\n    assert fahrenheit_to_celsius(212) == 100.0\n    assert fahrenheit_to_celsius(77) == 25.0\n    with pytest.raises(TypeError):\n        fahrenheit_to_celsius("string")\n    with pytest.raises(TypeError):\n        fahrenheit_to_celsius(None)\n\ndef test_celsius_to_kelvin():\n    assert celsius_to_kelvin(0) == 273.15\n    assert celsius_to_kelvin(-273.15) == 0.0\n    assert celsius_to_kelvin(100) == 373.15\n    with pytest.raises(TypeError):\n        celsius_to_kelvin("string")\n    with pytest.raises(TypeError):\n        celsius_to_kelvin(None)'

b'import argparse\nfrom converters import celsius_to_fahrenheit, fahrenheit_to_celsius, celsius_to_kelvin\n\ndef main():\n    parser = argparse.ArgumentParser(description=\'Convert temperature units.\')\n    parser.add_argument(\'temperature\', type=float, help=\'Temperature value to convert.\')\n    parser.add_argument(\'--from\',\'-f\', required=True, choices=[\'celsius\', \'fahrenheit\', \'kelvin\'], help=\'Source unit (celsius, fahrenheit, kelvin).\')\n    parser.add_argument(\'--to\',\'-t\', required=True, choices=[\'celsius\', \'fahrenheit\', \'kelvin\'], help=\'Target unit (celsius, fahrenheit, kelvin).\')\n    args = parser.parse_args()\n\n    if args.from == \'celsius\' and args.to == \'fahrenheit\':\n        result = celsius_to_fahrenheit(args.temperature)\n    elif args.from == \'fahrenheit\' and args.to == \'celsius\':\n        result = fahrenheit_to_celsius(args.temperature)\n    elif args.from == \'celsius\' and args.to == \'kelvin\':\n        result = celsius_to_kelvin(args.temperature)\n    else:\n        parser.error(f"Conversion from {args.from} to {args.to} is not supported. Supported conversions: Celsius→Fahrenheit, Fahrenheit→Celsius, Celsius→Kelvin")\n\n    print(f"{args.temperature} {args.from} is equal to {result} {args.to}.")\n\nif __name__ == \'__main__\':\n    main()'

b'import pytest\nimport sys\nfrom cli import main\n\ndef test_celsius_to_fahrenheit(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "25", "--from", "celsius", "--to", "fahrenheit"])\n    with pytest.capture_output() as cap:\n        main()\n    assert cap.stdout == "25 celsius is equal to 77.0 fahrenheit.\\n"\n\ndef test_fahrenheit_to_celsius(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "77", "--from", "fahrenheit", "--to", "celsius"])\n    with pytest.capture_output() as cap:\n        main()\n    assert cap.stdout == "77 fahrenheit is equal to 25.0 celsius.\\n"\n\ndef test_celsius_to_kelvin(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "0", "--from", "celsius", "--to", "kelvin"])\n    with pytest.capture_output() as cap:\n        main()\n    assert cap.stdout == "0 celsius is equal to 273.15 kelvin.\\n"\n\ndef test_unsupported_conversion(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "100", "--from", "fahrenheit", "--to", "kelvin"])\n    with pytest.raises(SystemExit) as excinfo:\n        main()\n    assert "Conversion from fahrenheit to kelvin is not supported" in str(excinfo.value)\n\ndef test_missing_temperature(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--from", "celsius", "--to", "fahrenheit"])\n    with pytest.raises(SystemExit) as excinfo:\n        main()\n    assert "the following arguments are required: temperature" in str(excinfo.value)\n\ndef test_missing_from(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "100", "--to", "fahrenheit"])\n    with pytest.raises(SystemExit) as excinfo:\n        main()\n    assert "the following arguments are required: --from" in str(excinfo.value)\n\ndef test_missing_to(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "100", "--from", "celsius"])\n    with pytest.raises(SystemExit) as excinfo:\n        main()\n    assert "the following arguments are required: --to" in str(excinfo.value)\n\ndef test_invalid_from_unit(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "100", "--from", "invalid", "--to", "fahrenheit"])\n    with pytest.raises(SystemExit) as excinfo:\n        main()\n    assert "invalid choice: invalid (choose from celsius, fahrenheit, kelvin)" in str(excinfo.value)\n\ndef test_invalid_to_unit(monkeypatch):\n    monkeypatch.setattr(sys, "argv", ["script.py", "--temperature", "100", "--from", "celsius", "--to", "invalid"])\n    with pytest.raises(SystemExit) as excinfo:\n        main()\n    assert "invalid choice: invalid (choose from celsius, fahrenheit, kelvin)" in str(excinfo.value)'

b'# temperature-conversion-library\n\nA simple library for converting temperature units between Celsius, Fahrenheit, and Kelvin.\n\n## Installation\n\nInstall the package using pip:\n\n```bash\npip install .\n```\n\n## Usage\n\n### As a Python library\n\nImport and use the conversion functions:\n\n```python\nfrom converters import celsius_to_fahrenheit, fahrenheit_to_celsius, celsius_to_kelvin\n\n# Example\nfahrenheit = celsius_to_fahrenheit(25)\ncelsius = fahrenheit_to_celsius(77)\nkelvin = celsius_to_kelvin(0)\n```\n\n### As a CLI tool\n\nUse the command-line interface to convert temperatures:\n\n```bash\npython cli.py --temperature <value> --from <unit> --to <unit>\n```\n\n**Supported units**: `celsius`, `fahrenheit`, `kelvin`  \n**Supported conversions**:\n- Celsius → Fahrenheit\n- Fahrenheit → Celsius\n- Celsius → Kelvin\n\n**Example**:\n```bash\npython cli.py --temperature 25 --from celsius --to fahrenheit\n# Output: 25 celsius is equal to 77.0 fahrenheit.\n```\n\n## Testing\n\nRun tests using pytest:\n\n```bash\npytest test_converters.py test_cli.py\n```\n\n## Limitations\n\n- This version only supports conversions between Celsius, Fahrenheit, and Kelvin for the following specific pairs:\n  - Celsius → Fahrenheit\n  - Fahrenheit → Celsius\n  - Celsius → Kelvin\n- Other conversions (e.g., Fahrenheit → Kelvin) are not implemented.\n- The CLI tool explicitly lists unsupported conversions with a message like:\n  `"Conversion from {args.from} to {args.to} is not supported"`'

**Issues Identified:**
1. **Incomplete Conversion Support**  
   The tool only supports three specific conversions:  
   - Celsius → Fahrenheit  
   - Fahrenheit → Celsius  
   - Celsius → Kelvin  
   It does **not** support conversions like:  
   - Fahrenheit → Kelvin  
   - Kelvin → Celsius  
   - Kelvin → Fahrenheit  
   These are valid use cases, and the code currently lacks the logic to handle them. The `converters.py` file does not provide functions for these conversions, but the tool should still inform users about this limitation.

2. **Error Message Ambiguity**  
   The error message `"Conversion from {args.from} to {args.to} is not supported"` is correct but could be improved by explicitly listing supported conversions (e.g., "Supported conversions: Celsius→Fahrenheit, Fahrenheit→Celsius, Celsius→Kelvin"). This would help users avoid confusion when encountering unsupported conversions.